---

- name: "Installing Apache in all remote servers"
  hosts: webservers
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - package:
        name: httpd
        state: present
    - service:
        name: httpd
        state: started
        enabled: yes
    - copy:
        dest: /var/www/html/index.html
        content: Hello World
